class Descent_PlasmaCannon : DSCWeapon
{
	Default
	{
		Weapon.SlotNumber 4;
		Tag "Plasma";
		DSCWeapon.WeaponName "Plasma Cannon";
		DSCWeapon.DisplayGraphic "WeapPlasma";
		DSCWeapon.SetupCrosshairs "Crosshair/weapon1", "Crosshair/weapon0";
	}
	
	action void A_FirePlasmaCannon()
	{
		A_ShootProjectile("DSCProj_Plasma", "PlasmaCannon/Fire", true, 0,0,0, (20,-10, -5));
		A_ShootProjectile("DSCProj_Plasma", useammo:true, 0,0,0, (20, 10, -5));
	}
	
	States
	{
		Ready:
			TNT1 A 1 A_WeaponReady();
		Loop;
		
		Fire:
			TNT1 A 6 A_FirePlasmaCannon();
		Goto Ready;
		
		Spawn:
			PLAS ABCDEFGHIJKLMNO 5;
		loop;
	}
}

class DSCProj_Plasma : DSCProjectile
{
	Default
	{	
		Radius 5;
		Height 5;
		Speed 30;
		DamageFunction 11 * DSCDMG;
		Scale 0.20;
		DSCProjectile.EnergyUse 0.125;
		Decal "Scorch";
	}
	
	States
	{
		Spawn:
			PLSB ABCDEF 4 Bright;
		loop;
	
		Crash:
		Death:
		XDeath:
			TNT1 A 0 
			{
				A_SetScale(1.0);
				A_StartSound("Projectile/Explode", flags:CHANF_OVERLAP);
			}
			EXDA ABCDE 2 Bright;
		stop;
	}
}
